# Generated by Django 4.1.3 on 2022-11-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
